server {
    listen      80;
    server_name localhost;
    root        /usr/share/nginx/html;
    index       index.html;

    # Activation de la compression gzip
    gzip on;
    gzip_types text/css application/javascript text/html;

    # Gestion des pages (multi-pages)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache des fichiers statiques (CSS, JS, images)
    location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
        expires 7d;
    }
}